import "../../globals.css";
import { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Administración - EcoAlliance",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`flex `}
      >

        <nav className="w-1/5 bg-blue-950 h-screen">
          <div className="flex justify-center mt-3">
            <Image src="/admin/dashboard/logo_eax.png" width={50} height={50} alt="Foto usuario" className=" rounded-full"/>
          </div>  
          <p className="text-center text-white text-md mt-5">Nombre administrador</p>
          <p className="text-center text-white  text-sm">Ecoalliance</p>
            <ul className="text-white mt-20">
              <li className=" pl-20 py-5 border border-slate-500"><Link href={"/admin/clientes"}>Clientes</Link></li>
              <li  className="pl-20 py-5 border border-slate-500"><Link href={"/admin/productos"}>Productos</Link></li>
              <li  className="pl-20 py-5 border border-slate-500"><Link href={"/admin/configuraciones"}>Configuraciones</Link></li>
              <li  className="pl-20 py-5 border border-slate-500"><Link href={"/admin/analisis"}>Análisis</Link></li>
              <li  className="pl-20 py-5 border border-slate-500"><Link href={"/admin/ventas"}>Ventas</Link></li>
            </ul>
        </nav>
        

        {children}

      </body>
    </html>
  );
}
